version: '3'

services:
  # The reverse proxy service (Traefik)
  reverse-proxy:
    image: traefik  # The official Traefik docker image
    command: --api --docker  # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"      # The HTTP port
      - "8080:8080"  # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # So that Traefik can listen to the Docker events

  # A container that exposes a simple API
  whoami:
    image: emilevauge/whoami  # A container that exposes an API to show its IP address
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
  whoami1:
    image: emilevauge/whoami
    labels:
      - traefik.enable=true
      - traefik.sample.frontend.rule=PathPrefixStrip:/testpath
      - traefik.sample.port=80
      - traefik.sample1.frontend.rule=PathPrefixStrip:/testpath1
      - traefik.sample1.port=80
#Test segment behaviour. Mutiple segments can be similarly implemented.
#      - traefil.docker.network=traefik-net
#    networks: 
#      - traefik-net

