version: '3'

services:
  # The reverse proxy service (Traefik)
  reverse-proxy:
    image: traefik  # The official Traefik docker image
    command: 
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"      # The HTTP port
      - "8080:8080"  # The Web UI (enabled by --api)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  # So that Traefik can listen to the Docker events

  # A container that exposes a simple API
  whoami1:
    image: emilevauge/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami1.entrypoints=web
      - "traefik.http.routers.whoami1.rule=Path(`/traefik`)"
      - "traefik.http.services.whoami1.loadbalancer.server.port=80"
    

#Test segment behaviour. Mutiple segments can be similarly implemented.
#      - traefil.docker.network=traefik-net
#    networks: 
#      - traefik-net
